import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "../style/main.scss";
import Main from "@/component/Main";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<Main>{children}</Main>
			</body>
		</html>
	);
}
